name: Turbo Campaign
date: September 2023
setup:
  os: 
  cpu: 
  ram: 
  timeout: 400
  memout: 
source:
  path: statistics.csv
  format: csv
data:
  mapping:
    experiment_ware: configuration
    cpu_time: time
    input: 
      - model
      - data_file